version: 2.1
jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: "Build front-end"
          command:  |
            cd frontend
            npm install
            npm i caniuse-lite browserslist
            npm run build
            exit 1
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build


  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: "Build back-end"
          command:  |
            cd backend
            npm install @types/jasmine
            npm install
            npm run build
            exit 1
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

workflows:
  sayworkflow:
    jobs:
      - build-frontend
      - build-backend
    